---
# include_tasks file

# NOTE! Add as pre-task to source env variables stored in indexer-config repo
- name: Create private config directory with restricted permissions
  ansible.builtin.file:
    path: "{{ private_conf_dir }}"
    state: directory
    mode: '0700'
    owner: "{{ ansible_env.USER }}"
  become: false

- name: Clone private configuration repository
  ansible.builtin.git:
    repo: "{{ config_repo.prefix }}/{{ config_repo.name }}.git"
    dest: "{{ private_conf_dir }}/{{ config_repo.name }}"
    version: "{{ config_repo.branch }}"
    accept_hostkey: true
  become: false
  register: git_clone

- name: Set config file path fact
  ansible.builtin.set_fact:
    config_file_path: "{{ private_conf_dir }}/{{ config_repo.name }}/{{ (app_environment in ['local', 'staging']) | ternary('staging', 'prod') }}.sh"

- name: Verify configuration file exists
  ansible.builtin.stat:
    path: "{{ config_file_path }}"
  register: config_file
  failed_when: not config_file.stat.exists

- name: Read configuration file
  ansible.builtin.slurp:
    src: "{{ config_file_path }}"
  register: config_file_content
  become: false

- name: Parse configuration variables
  ansible.builtin.set_fact:
    sourced_env: "{{ sourced_env | default({}) | combine({ item.split('=')[0]: item.split('=')[1:] | join('=') }) }}"
  loop: "{{ (config_file_content['content'] | b64decode).split('\n') }}"
  when: item is match("^[A-Z0-9_]+=.*") and not item.startswith('#')
  no_log: true

- name: Remove private config directory
  ansible.builtin.file:
    path: "{{ private_conf_dir }}"
    state: absent
  become: false
