{
 "title": "Server stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.cpu.pct.*"
    }
   ]
  },
  {
   "title": "15 minute load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.load.15.*"
    }
   ]
  },
  {
   "title": "Memory percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.vm.pct.*"
    }
   ]
  },
  {
   "title": "Swap percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.swap.pct.*"
    }
   ]
  },
  {
   "title": "Disk percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.disk.pct.*.*"
    }
   ]
  }
 ]
}