{
 "title": "story-indexer (all realms)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "realm", "query": "prod,staging,pbudne,pgulley" }
  ]
 },
 "panels": [
  {
   "title": "fetcher HTTP status (stories per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.story-indexer.fetcher.stories.*.rate"
    }
   ]
  },
  {
   "title": "Fetcher worker containers running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.docker-stats.service.running.name_fetcher-worker"
    },
    {
     "target": "stats.gauges.mc.$realm.story-indexer.docker-stats.service.running.name_queue-rss"
    }
   ]
  },
  {
   "title": "Parser status (stories per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.story-indexer.parser.stories.*.rate"
    }
   ]
  },
  {
   "title": "parser stories per second by Worker status (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scale(stats.timers.mc.$realm.story-indexer.parser.message.*.count, 0.10)"
    }
   ]
  },
  {
   "title": "Importer status (stories/second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.story-indexer.importer.stories.*.rate"
    }
   ]
  },
  {
   "title": "Importer stories per second by Worker status (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scale(stats.timers.mc.$realm.story-indexer.importer.message.*.count, 0.1)"
    }
   ]
  },
  {
   "title": "Archiver files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.story-indexer.archiver.batches.*.count"
    }
   ]
  },
  {
   "title": "Archiver message status/sec (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scale(stats.timers.mc.$realm.story-indexer.archiver.message.*.count, 0.1)"
    }
   ]
  },
  {
   "title": "Queue messages ready",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.ready.*"
    }
   ]
  },
  {
   "title": "Queue messages unacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.unacked.*"
    }
   ]
  },
  {
   "title": "Document count by index (1K=1000)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.stats.docs.*"
    }
   ]
  },
  {
   "title": "Primary index size in bytes (1K=1024)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.stats.pri-size.*"
    }
   ]
  },
  {
   "title": "Deleted document count by Index (1K=1000)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.stats.deleted.*"
    }
   ]
  },
  {
   "title": "messages sent per second (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.story-indexer.*.sent-msgs.*.rate"
    }
   ]
  },
  {
   "title": "Index health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.health.*"
    }
   ]
  },
  {
   "title": "app max run time (minutes)",
   "type": "graph",
   "description": "max run time in minutes\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "target": "scale(stats.timers.mc.$realm.story-indexer.*.main_loop.upper, 0.001)"
    }
   ]
  },
  {
   "title": "parser metadata extract times stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.parser.extract.*.mean"
    }
   ]
  }
 ]
}