{
 "title": "story-indexer alerts",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Stories Added to ES by hour",
   "type": "graph",
   "description": "based on ES document count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "sumSeries(summarize(nonNegativeDerivative(stats.gauges.mc.prod.story-indexer.elastic-stats.indices.indices.primaries.docs.count.name_mc_search*), '1h', 'sum', false))"
    }
   ]
  },
  {
   "title": "sum of all input & delay queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-in, stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-delay, stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-fast)"
    }
   ]
  },
  {
   "title": "ES unhealthy indices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.indices.health.color_red"
    },
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.indices.health.color_yellow"
    }
   ]
  },
  {
   "title": "all quarantine queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-quar)"
    }
   ]
  }
 ]
}