---
app_name: "story-indexer"
app_environment: "{{ env }}"

#### vars for ansible-elasticsearch (all start with es_)
# key/values copied to elasticsearch.yml output file:
es_config:
  # PLEASE ADD ITEMS IN SORTED ORDER BELOW THIS LINE!
  bootstrap.memory_lock: true
  cluster.name: "mc_es_cluster"
  cluster.initial_master_nodes: "{{ mc_es_seed_hosts }}"
  # seed hosts is list of master-eligible nodes; port is defaulted from transport.port
  # (NOTE! if you add ports to mc_es_seed_hosts you'll break the mc_es_master test below)
  discovery.seed_hosts: "{{ mc_es_seed_hosts }}"
  http.host: 0.0.0.0 # allow from off-host connections
  # node.name defaults to inventory_hostname
  node.roles: "{{ mc_es_node_roles }}"
  # PLEASE ADD ITEMS ABOVE IN SORTED ORDER!
  # Enable security features
  xpack.security.enabled: false
  xpack.security.enrollment.enabled: false
  # Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
  # xpack.security.http.ssl:
  #   enabled: false
  # # Enable encryption and mutual authentication between cluster nodes
  # xpack.security.transport.ssl:
  #   enabled: false

es_templates: false
es_templates_fileglob: ""
es_version: 8.17.3
es_version_lock: true

################ MC specific vars (start with mc_)
# elastic search specific vars (just about everything) should start with mc_es_
mc_es_master: "{{ mc_es_seed_hosts }}"
mc_es_mappings_dynamic: false
mc_es_node_roles: "{% if mc_es_master %}{{ mc_es_node_roles_master }}{% else %}{{ mc_es_node_roles_data }}{% endif %}"
mc_es_node_roles_data: ["data"]
mc_es_node_roles_master: ["master", "data"]
