# only what we use...

import typing as _t

_JSON = dict[str, _t.Any]
_LIST_JSON = list[_JSON]

class _GetDefinitionsReturn(_t.TypedDict):
    bindings: _LIST_JSON
    exchanges: _LIST_JSON
    queues: _LIST_JSON

class AdminAPI:
    def __init__(self, url: str, auth: tuple[str, str]): ...
    def _api_get(self, url: str) -> _t.Any: ...
    def get_definitions(self) -> _GetDefinitionsReturn: ...
    def list_exchanges(self) -> _LIST_JSON: ...
    def list_nodes(self) -> _LIST_JSON: ...
