"""
partial stub file for PyPI statsd_client
"""

class StatsdClient:
    def __init__(self, host: str, port: int | None, prefix: str | None) -> None: ...
    def incr(self, bucket: str, delta: int) -> None: ...
    def gauge(self, bucket: str, value: int | float) -> None: ...
    def timing(self, bucket: str, ms: int | float) -> None: ...
